### ISSUE TITLE
Some IP cameras upload non jpg files, such as video files.  Don't upload all files to onedrive as jpg files.

### ISSUE THREAD

**Issue by mazudo** [ms-iot/securitysystem#73]
The Security system a customer used is this one https://www.lorextechnology.com/HD-DVR-Security-system/HD-security-camera-system-with-full-1080p-recording-resolution/prod930002.p#downloadsTab

The Lorex tried to upload videos, but the security gateway renamed them to .jpg (and therefore were not viewable).

**Comment by mwmckee** [comment]
This will need a little investigation. The code never directly does anything to file extensions - it simply takes files wholesale and uploads them. Venturing a guess, it's because the file type used by this camera isn't in the list of associated file extensions in the app manifest. I would expect Windows or the app to simply not touch those files, but maybe it alters the extension when it grabs them.

**Comment by mazudo** [comment]
Enhancement.  Closing as won't fix for now.
